options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _IMAGE_NAME: us-central1-docker.pkg.dev/${PROJECT_ID}/idaas-repo/idaas

steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "${_IMAGE_NAME}", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_IMAGE_NAME}"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - run
      - deploy
      - idaas-staging
      - --image=${_IMAGE_NAME}
      - --region=us-central1
      - --allow-unauthenticated

images:
  - "${_IMAGE_NAME}"
